version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: remove node_modules
          command: rm -fr node_modules
      
      - run:
          name: Install dependencies 
          command: npm install
      
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies 
          command: npm run postinstall
      
      - run:
          name: Run test  
          command: npm run test

      - store_test_results:
          path: target/site/serenity
     
      - store_artifacts:
          path: target/site/serenity
          destination: .
      - store_artifacts:
          path: ./*