version: 2.1
jobs:
  integrationtest:
    docker:
      - image: cimg/openjdk:14.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: java --version
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: Check current version of node
          command: node -v


      - run:
          name: Install dependencies 
          command: npm install
      
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies 
          command: npm run postinstall

      - run:  
          command: ./startwebserver.sh
          background: true

      - run:
          shell: /bin/sh
          command: |
              wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:8080
     
      
      - run:
          name: Run test  
          command: npm run test
     
      - store_test_results:
          path: target

      # host latest report in AWS S3
      - aws-s3/copy:
          arguments: '--recursive --acl public-read-write'
          from: target/site/serenity
          to: 's3://serenitybdd'
      - persist_to_workspace:
          root: .
          paths:
            - package.json

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  version: 2
  integrationtest:
    jobs:
      - integrationtest
