version: 2.1
jobs:
  integrationtest:
    docker:
      - image: cimg/base:2021.04
    working_directory: ~/repo
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies 
          command: npm install
      
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies 
          command: npm run postinstall
      
      - run:
          name: Run test  
          command: npm run test
     
      - store_test_results:
          path: target

      # host latest report in AWS S3
      - aws-s3/copy:
          arguments: '--recursive --acl public-read-write'
          from: target/site/serenity
          to: 's3://serenitybdd'
      - persist_to_workspace:
          root: .
          paths:
            - package.json

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  version: 2
  integrationtest:
    jobs:
      - integrationtest
