version: 2.1
jobs:
  integrationtest:
    docker:
      - image: timbru31/java-node:latest

    parameters:
      env:
        type: enum
        enum: ['stage', 'preprod']
        default: 'stage'
    environment:
      ENVIRONMENT: << parameters.env >>
    working_directory: ~/repo
    steps:
      - build-tools/install-ci-tools
      - checkout      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies 
          command: npm install
      
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
     
      - run:  
          command: ./startwebserver.sh
          background: true

      - run:
          shell: /bin/sh
          command: sleep 500 
     
      - run:
          name: Run test  
          command: npm run test:${ENVIRONMENT}
     
      - store_test_results:
          path: target

      # host latest report in AWS S3
      - aws-s3/copy:
          arguments: '--recursive --acl public-read-write'
          from: target/site/serenity
          to: 's3://serenitybdd'
      - persist_to_workspace:
          root: .
          paths:
            - package.json

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  build-tools: circleci/build-tools@3.0.0

workflows:
  version: 2
  integrationtest:
    jobs:
      - integrationtest:
            context:
              - CIRCLE_CI_AWS_IAM
            filters:
              branches:
                only:
                  - master
                  - /circleci-.*/
